import React from "react";
import ReactDOM from "react-dom/client";
import App from "./App";
import "./Coponents/Home/Home.css";
import "./Coponents/Header/Header.css";
import "./Coponents/About/Education/Education.css";
import "./Coponents/About/Skills/Skills.css";
import "./Coponents/Projects/Projects.css";
import "./Coponents/Contact/Contact.css";
const root = ReactDOM.createRoot(document.getElementById("root"));
root.render(<App />);
